### ISSUE TITLE
Use the URL www.openstreetmap.org instead of osm.org

### ISSUE THREAD

**Issue by ngosang** [osmlab/show-me-the-way#38]
I'm usually logged in www.openstreetmap.org and I don't want to login again.

**Comment by tmcw** [comment]
I'm confused: you don't need to log into show-me-the-way. Is it prompting for a login?

**Comment by ngosang** [comment]
> Is it prompting for a login?

No, but when I click in the user name of one edition the URL points to osm.org.

**Comment by iandees** [comment]
osm.org will redirect to openstreetmap.org. Either way, it's the same site with the same login cookies.

**Comment by ngosang** [comment]
> Either way, it's the same site with the same login cookies.

I need to login in both sites. I'm using Firefox.

**Comment by iandees** [comment]
You might want to file a bug on https://github.com/openstreetmap/openstreetmap-website then. It sounds like a browser problem. On my Mac's Firefox, Chrome, and Safari osm.org redirects to openstreetmap.org and my logged in session works fine.

**Comment by ngosang** [comment]
That is because you are not using the HTTPS version.
* http://osm.org => redirects to http://www.openstreetmap.org
* https://osm.org => **no redirection**

Try using the HTTPS version of show-me-the-way
 https://osmlab.github.io/show-me-the-way/ and you will see the problem.

**Comment by iandees** [comment]
Ah, that's an important part of the bug report :smile:.

osm.org doesn't have a valid SSL certificate so you shouldn't be seeing osm.org at all, you should be seeing a browser error.

Now that we make a decent attempt to support SSL it probably makes sense to link to openstreetmap.org so we don't run into SSL errors.

**Comment by ngosang** [comment]
> osm.org doesn't have a valid SSL certificate so you shouldn't be seeing osm.org at all, you should be seeing a browser error.

I added an exception long time ago and I didn't remember.

**Comment by ngosang** [comment]
@iandees you went too fast. There are more changes:
index.html => https://github.com/osmlab/show-me-the-way/blob/ad7a66b17ab0114ab975bcb71f8ffb188c099949/index.html#L29
chromecast/receiver.html => https://github.com/osmlab/show-me-the-way/blob/699cb272ae468157cc3965556590c1e1e4f4a641/chromecast/receiver.html#L29

**Comment by iandees** [comment]
Fixed the missing link in index.html. chromecast/receiver.html should never be seen by a browser outside of a Chromecast.

**Comment by ngosang** [comment]
Thanks.
