### ISSUE TITLE
Filter for regions

### ISSUE THREAD

**Issue by kvlahromei** [osmlab/show-me-the-way#40]
Hi there,

it would be nice, if users could set filters to monitor only edits that touch a custom bbox. This would allow everybody to set a focus on a dedicated region (e.g. your country or state) which makes IMHO sense esp. for local events like conferences.

**Comment by iandees** [comment]
You can do this by going to https://osmlab.github.io/show-me-the-way/bbox.html, moving the bounding box to your area of interest, and clicking the URL that shows up at the bottom of the map.

**Comment by kvlahromei** [comment]
@iandees thanks :-)
