### ISSUE TITLE
When bounds are given, whole planet is queried anyway - this is slow.

### ISSUE THREAD

**Issue by Piskvor** [osmlab/show-me-the-way#49]
Even if a bounding box is requested through the `#bounds=` parameter, the query for updates still loads the whole planet's changes and parses that. A single update could be multiple MBs, most of which is thrown away - on a bad connection, this is especially palpable.

If a bounding box exists, updates should be polite and use it.

**Comment by iandees** [comment]
Last I checked the augmented diffs thing didn't support bounding box queries (even though it said it did 😄 ). That was a while ago, though, so maybe it has been fixed.

**Comment by Piskvor** [comment]
It has. PR forthcoming :)

**Comment by Piskvor** [comment]
Alas, we were both right. Bounding box queries *are* supported, but somewhat-silently fail on large bboxes. #50 doesn't work for e.g. country-sized bbox; I propose a dumb, and perhaps overcautious heuristic for the filtering: #52
