### ISSUE TITLE
HTTP Error 401 for Mapbox tiles

### ISSUE THREAD

**Issue by ltog** [osmlab/show-me-the-way#55]
When trying to watch https://osmlab.github.io/show-me-the-way/ , I see ways being drawn but the background is black.

The problem seems to be HTTP 401 errors for the tiles from Mapbox.

**Comment by iandees** [comment]
Looks like the API key that's in there right now expired or is not valid anymore.

**Comment by iandees** [comment]
Updated to a newer Mapbox style. 👍

**Comment by ltog** [comment]
@iandees : Very nice, thank you for the fast fix! 👍
