### ISSUE TITLE
Show certain nodes on the map

### ISSUE THREAD

**Issue by Raytlye** [osmlab/show-me-the-way#56]
Currently "show me the way" only displays ways and polygons. I would like to try to show nodes with certain tags as well. I know through @iandees that "show me the way" is already quite busy handling all the ways that get updated in real time. My knowledge is quite limited on javascript so does anyone have ideas on where to start?

**Comment by Carniv0re** [comment]
Leaving a comment, this is interesting!

**Comment by sfkeller** [comment]
@iandees : What do you think? Did someone already try to extend this?

**Comment by iandees** [comment]
Nope, I haven't seen a pull request for this yet.

**Comment by sfkeller** [comment]
We're having hard time to understand the source code. A change like this issue seems to affect several functions. And it's my idea use the bbox in order to reduce the input. Any sparring partner around to discuss the code extensions?

**Comment by sfkeller** [comment]
@iandees: Just digged more into the code. There's a show stopper at osm-stream since it seems to be unable to extract Node tags: https://github.com/osmlab/osm-stream/pull/13 . Do you know the status of this issue and your pull request?

**Comment by iandees** [comment]
This was done in #57.
