### ISSUE TITLE
Bug in bbox

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmlab/show-me-the-way#58]
Hi, I found a bug in the bbox page [1]. When an area is selected and the link is created in the link remain the element bbox [2] and this will not open a new page with the bounding box selected. So it's just needed to delete the word "bbox" on the resulting link.
Thanks for all your work.

[1] https://osmlab.github.io/show-me-the-way/bbox
[2] https://osmlab.github.io/show-me-the-way/bbox#bounds=33.72,5.97,54.26,22.14
[3] https://osmlab.github.io/show-me-the-way/#bounds=33.72,5.97,54.26,22.14

**Comment by iandees** [comment]
Hi Lorenzo. I'm not sure where you found the URL `https://osmlab.github.io/show-me-the-way/bbox` (and equally not sure why it works ... that must be a bug in GitHub pages), but the URL should be [https://osmlab.github.io/show-me-the-way/bbox.html](https://osmlab.github.io/show-me-the-way/bbox.html).

When you use the correct URL, the link generates correctly.

**Comment by LorenzoStucchi** [comment]
Ok sorry probably I save it in some strange way. So thanks you for the answer and good work

**Comment by iandees** [comment]
Thanks for pointing it out! It's surprising to me that GitHub let that URL work. I'll check with them on how to solve that problem.

**Comment by iandees** [comment]
I think I fixed this in 91be3cd.
