### ISSUE TITLE
Incorrect URLs if navigated to bbox page without `.html` ending

### ISSUE THREAD

**Issue by jaller94** [osmlab/show-me-the-way#59]
### Steps to reproduce
1. Open https://osmlab.github.io/show-me-the-way/bbox (without `.html`)
2. Select an area
3. Navigate to the link

### Expected
`https://osmlab.github.io/show-me-the-way/#bounds=49.196064000723794,-123.211669921875,49.31258949637,-122.904052734375`
The slideshow starts for the selected area.

### Actual
`https://osmlab.github.io/show-me-the-way/bbox#bounds=49.196064000723794,-123.211669921875,49.31258949637,-122.904052734375`
It brings you to the bbox selection page.

**Comment by iandees** [comment]
There's not much I can do about this. Where are you getting the URL without the .html suffix?

**Comment by iandees** [comment]
Dupe of #58.

**Comment by jaller94** [comment]
Typed it off a screen at a HOT event. While the presenter used the URL with `.html`, I did not type it, as it usually doesn’t matter.

**Comment by iandees** [comment]
I think I fixed this in 91be3cd. Give it a shot.
