### ISSUE TITLE
Map doesn't load on bounding box selector page

### ISSUE THREAD

**Issue by tech189** [osmlab/show-me-the-way#67]
The satellite view on the [bbox.html](https://osmlab.github.io/show-me-the-way/bbox.html) page doesn't load, getting 410 errors!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10728085/108054377-7a7d8480-7046-11eb-972c-8df63febe683.png">

**Comment by iandees** [comment]
Fixed in 5f98144.
