### ISSUE TITLE
Allow Mapbox token to be set via url param

### ISSUE THREAD

**Issue by planemad** [osmlab/show-me-the-way#88]
The current token on http://osmlab.github.io/show-me-the-way/ no longer works and gives a 403
https://github.com/osmlab/show-me-the-way/blob/cb19e0f7efa9a7baf680fae3f7c1125ce0fa7f0c/bbox.html#L50

To make the app future proof, we could allow setting a token via the url with `access_token=` so that anyone can use their own personal token to override the default.

**Comment by iandees** [comment]
This is a valid Mapbox API token on a valid Mapbox account (with valid CORS limitations), so there's some other problem with Mapbox here.

**Comment by planemad** [comment]
You are right, seems to be working now
